#!/bin/sh
#
# unimark: Browser independent bookmarking tool
#
# Dependencies: amenu/dmenu/rofi, xdotool, xsel/xclip, grep & find

#===============================================================================
#                             Config
#===============================================================================

BOOKMARKS_PATH=$GIT/own/magpie-private/.local/share/bookmarks
DMENU=amenu

#===============================================================================
#                             Script
#===============================================================================

bookmark() {
   echo "$1" > "$(find $4 -type d -name \
      "$3")"/"$(echo "$2" | sed 's/\///g')".url
}
get_title() {
   # curl -Ls "$1" |
   #    tr -d '\n' |
   #    grep -iPo '(?<=<title>)(.*)(?=</title>)'
   xdotool getactivewindow getwindowname
}
get_url() {
   if xdotool getactivewindow getwindowname | grep "qutebrowser" > /dev/null; then
      xdotool sleep 0.3 key y p
   else
      xdotool key F6
      xdotool sleep 0.3 key Control+c
      xdotool key F6
      xdotool getactivewindow getwindowname | grep "Brave" > /dev/null &&
         xdotool key F6
   fi
   sleep 0.3
   xsel -b -o || xclip -se c -o
}
prompt_title() { : | $DMENU -p "Title"; }
prompt_location() { find $1 -type d | awk -F / '{print $NF}' | $DMENU; }

main() {
   if LOCATION=$(prompt_location "$BOOKMARKS_PATH") &&
      TITLE=$(prompt_title); then
      URL=$(get_url)
      [ -z "$TITLE" ] && TITLE=$(get_title)
      bookmark "$URL" "${TITLE% — *}" "$LOCATION" $BOOKMARKS_PATH
   fi
}
main
