#!/bin/sh
#
# unimark: Browser independent bookmarking tool
#
# Dependencies: dmenu/rofi, xdotool, xsel/xclip, curl, grep, & find

#===============================================================================
#                             Config
#===============================================================================

BOOKMARKS_PATH=$GIT/own/magpie-private/.local/share/bookmarks
DMENU=dmenu

#===============================================================================
#                             Script
#===============================================================================

get_title() { curl -s "$1" | grep -iPo '(?<=<title>)(.*)(?=</title>)'; }

get_url() {
   if xdotool getactivewindow getwindowname | grep "qutebrowser" > /dev/null; then
      xdotool sleep 0.3 key y p
   else
      xdotool key F6
      xdotool sleep 0.3 key Control+c
      xdotool key F6
      xdotool getactivewindow getwindowname | grep "Brave" > /dev/null &&
         xdotool key F6
   fi
   sleep 0.3
   xsel -b -o || xclip -se c -o
}

if LOCATION=$(find $BOOKMARKS_PATH -type d | awk -F / '{print $NF}' | $DMENU) &&
   TITLE=$(: | $DMENU -p "Title"); then
   URL=$(get_url)
   [ -z "$TITLE" ] && TITLE=$(get_title "$URL")
   echo "$URL" > "$(find $BOOKMARKS_PATH -type d -name "$LOCATION")"/"$TITLE".url
fi
